name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
      - run: echo "this job is skipped"
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}> | <{run_url}|View Run>"
          footer: "Linked Repo <{repo_url}|{repo}>"
          # Only alert on failure to prevent spamming the channel
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: "example.com"